services:
  # wa_gateway_prod:
  #   build:
  #     context: ./wa-gateway
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "80:8000"

  wa_gateway_dev:
    build:
      context: ./wa-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: fastapi dev src/main.py --host 0.0.0.0
    volumes:
      - ./wa-gateway/src:/app/src

  rabbitmq:
    image: rabbitmq:4.1.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  queue_consumer:
    build:
      context: ./queue-consumer
      dockerfile: ./Dockerfile
    volumes:
      - ./queue-consumer:/app
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8001:8000"
    command: fastapi dev src/main.py --host 0.0.0.0
    volumes:
      - ./backend/src:/app/src