services:
  rabbitmq:
    image: rabbitmq:4.2.0-management
    expose: ["5672"]
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  wa_gateway_dev:
    build:
      context: ../wa-gateway
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - "8000:8000"
    command: fastapi run src/main.py --host 0.0.0.0
    depends_on:
      - rabbitmq
  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    expose: ["8000"]
    command: fastapi run src/main.py --host 0.0.0.0
  queue_consumer:
    build:
      context: ../queue-consumer
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    depends_on:
      - rabbitmq
      - backend
  frontend:
    build:
      context: ../frontend
      dockerfile: ./Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: npm run serve
    volumes:
      - ../frontend/src:/app/src
    expose: ["5173"]
    stdin_open: true
    tty: true
    depends_on:
      - backend
  caddy:
    image: caddy:2.10.2
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - frontend
      - backend
